In [19]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100 (inclusive)
arr = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns using transposition
interchanged_arr = arr.T

# Print the original array and the interchanged array
print("Original array:")
print(arr)

print("\nArray with rows and columns interchanged:")
print(interchanged_arr)

















Original array:
[[43 53 49]
 [40 33 32]
 [72  2 34]]

Array with rows and columns interchanged:
[[43 40 72]
 [53 33  2]
 [49 32 34]]


In [15]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

# Generate a 1D NumPy array with 10 elements
arr_1d = np.arange(10)

# Reshape into a 2x5 array
arr_2d = arr_1d.reshape(2, 5)

# Reshape into a 5x2 array
arr_5x2 = arr_1d.reshape(5, 2)

# Print the original and reshaped arrays
print("Original 1D array:")
print(arr_1d)

print("\nReshaped array (2x5):")
print(arr_2d)

print("\nReshaped array (5x2):")
print(arr_5x2)




Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped array (2x5):
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped array (5x2):
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [6]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np

# Create a 4x4 NumPy array with random float values
arr_4x4 = np.random.rand(4, 4)

# Add a border of zeros using padding
padded_arr = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the original and padded arrays
print("Original 4x4 array:")
print(arr_4x4)

print("\nArray with border of zeros (6x6):")
print(padded_arr)



Original 4x4 array:
[[0.50697335 0.9054743  0.46159831 0.41124167]
 [0.23824354 0.65649219 0.66690368 0.2163288 ]
 [0.78103401 0.37352841 0.53950932 0.79061438]
 [0.75512319 0.33678244 0.86973639 0.63028881]]

Array with border of zeros (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.50697335 0.9054743  0.46159831 0.41124167 0.        ]
 [0.         0.23824354 0.65649219 0.66690368 0.2163288  0.        ]
 [0.         0.78103401 0.37352841 0.53950932 0.79061438 0.        ]
 [0.         0.75512319 0.33678244 0.86973639 0.63028881 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [7]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

# Create an array using np.arange
arr = np.arange(10, 61, 5)  # Start, stop (not inclusive), step

# Print the array
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


In [9]:
#5)Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.

In [ ]:
# Importing necessary library
import numpy as np

# Creating a NumPy array containing strings
x = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype=np.str)

# Displaying the content of the original array
print("\nOriginal Array:")
print(x)

# Checking if each element contains digits only
r1 = np.char.isdigit(x)

# Checking if each element contains lower case letters only
r2 = np.char.islower(x)

# Checking if each element contains upper case letters only
r3 = np.char.isupper(x)

# Displaying results
print("Digits only =", r1)
print("Lower cases only =", r2)
print("Upper cases only =", r3)


In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.



In [17]:
import numpy as np

# Create a NumPy array of words
words_arr = np.array(['hello', 'world', 'python'])

# Function to insert spaces between characters
def insert_spaces(word):
  return ' '.join(list(word))

# Apply the function to each element using vectorization
spaced_words = np.vectorize(insert_spaces)(words_arr)

# Print the original and spaced-out arrays
print("Original array:")
print(words_arr)

print("\nArray with spaces between characters:")
print(spaced_words)


Original array:
['hello' 'world' 'python']

Array with spaces between characters:
['h e l l o' 'w o r l d' 'p y t h o n']


In [18]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

# Create two 2D NumPy arrays with random values
arr1 = np.random.randint(1, 10, size=(3, 4))
arr2 = np.random.randint(1, 10, size=(3, 4))

# Perform element-wise operations
added_arr = arr1 + arr2
subtracted_arr = arr1 - arr2
multiplied_arr = arr1 * arr2
divided_arr = arr1 / arr2  # Caution: Handle potential division by zero

# Print the original arrays and the results
print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nElement-wise addition:")
print(added_arr)

print("\nElement-wise subtraction:")
print(subtracted_arr)

print("\nElement-wise multiplication:")
print(multiplied_arr)

print("\nElement-wise division:")
print(divided_arr)


Array 1:
[[3 8 3 4]
 [4 4 3 7]
 [7 3 1 7]]

Array 2:
[[4 5 8 7]
 [5 1 3 7]
 [3 9 8 9]]

Element-wise addition:
[[ 7 13 11 11]
 [ 9  5  6 14]
 [10 12  9 16]]

Element-wise subtraction:
[[-1  3 -5 -3]
 [-1  3  0  0]
 [ 4 -6 -7 -2]]

Element-wise multiplication:
[[12 40 24 28]
 [20  4  9 49]
 [21 27  8 63]]

Element-wise division:
[[0.75       1.6        0.375      0.57142857]
 [0.8        4.         1.         1.        ]
 [2.33333333 0.33333333 0.125      0.77777778]]


In [20]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np




# Method 1: Slicing
diagonal_elements_slice = identity_matrix.diagonal()

# Method 2: Indexing
diagonal_elements_index = identity_matrix[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

# Print the identity matrix and diagonal elements
print("Identity matrix:")
print(identity_matrix)

print("\nDiagonal elements (using slicing):")
print(diagonal_elements_slice)

print("\nDiagonal elements (using indexing):")
print(diagonal_elements_index)


Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements (using slicing):
[1. 1. 1. 1. 1.]

Diagonal elements (using indexing):
[1. 1. 1. 1. 1.]


In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.



In [21]:
import numpy as np

def is_prime(num):
  """Efficiently checks if a number is prime."""
  if num <= 1:
    return False
  for i in range(2, int(np.sqrt(num)) + 1):
    if num % i == 0:
      return False
  return True

# Generate a NumPy array of 100 random integers
arr = np.random.randint(0, 1001, size=100)

# Find prime numbers using vectorization and boolean indexing
prime_mask = np.vectorize(is_prime)(arr)  # Apply is_prime function to each element
prime_numbers = arr[prime_mask]  # Select elements where prime_mask is True

# Print the original array and the prime numbers
print("Original array:")
print(arr)

if prime_numbers.size > 0:
  print("\nPrime numbers:")
  print(prime_numbers)
else:
  print("\nNo prime numbers found in the array.")


Original array:
[473 490 149 620 385 331 648 280 309 282 227  61 120 896 878 851 414 257
 412 599 787 870 255 111 931 990  85 545 177 655 644 349 901 234 300 317
 506  93 713 239 758 273 458 229 728 426 590 949 407 758 984 707 666 255
  63 783  52 470 424 899 485 791 746 652 982 729 376 346 244 306 436 591
 738 469 703 695 266 380 628 260 560 400 272 613 853 253 484 343 462 452
  96 431 896 526  82 924 743 621 590 594]

Prime numbers:
[149 331 227  61 257 599 787 349 317 239 229 613 853 431 743]


In [22]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages
import numpy as np

def weekly_averages(temperatures):
  """Calculates and returns weekly averages from a temperature array."""
  # Assuming 30 days in a month and 7 days in a week
  num_weeks = int(temperatures.size / 7)
  weekly_avgs = np.zeros(num_weeks)  # Initialize array for weekly averages

  for week in range(num_weeks):
    # Calculate average for each week
    weekly_avgs[week] = temperatures[week * 7: (week + 1) * 7].mean()

  return weekly_avgs

# Create a NumPy array representing daily temperatures (adjust as needed)
temperatures = np.random.randint(10, 30, size=30)  # Example temperatures

# Calculate weekly averages
weekly_avg_temps = weekly_averages(temperatures)

# Print the daily temperatures and weekly averages
print("Daily temperatures:")
print(temperatures)

print("\nWeekly average temperatures:")
print(weekly_avg_temps)


Daily temperatures:
[22 15 22 10 18 13 20 25 23 24 12 19 14 19 16 12 29 27 23 12 22 12 28 28
 28 18 24 18 10 15]

Weekly average temperatures:
[17.14285714 19.42857143 20.14285714 22.28571429]
